### PR TITLE
remove server part of edict_t from mod memory

### PR DESCRIPTION
**Pull request by angeld29**
in QVM Version 16 mod must use gedict without pointer to serverside part
fix comportability with previous QVM Api versions,
fix working sv_pr2references=0 for 32 bit and QVM mode

### CODE REVIEW

**Comment by meag** [comment]
Thanks for this - I'll need to digest it quite a bit.
Out of interest, what QVM mod are you running?

**Comment by angeld29** [comment]
> Thanks for this - I'll need to digest it quite a bit.
main change in progs.h in  edict_t
all other for support this change
and minor for correct working old mods with API having new params(int flags)
> Out of interest, what QVM mod are you running?
 im develop TF2003( Team Fortress)
last commit with slide fix needed for tf  map muskrat2, muskrat4 
it have not vertical wall outdoor

**Comment by meag** [comment]
Thanks

"mod must use gedict without pointer to serverside part" ... why is that?  Did it work in previous versions?  Trying to gauge exactly what I broke :)

**Comment by angeld29** [comment]
> 
> 
> Thanks
> 
> "mod must use gedict without pointer to serverside part" ... why is that? Did it work in previous versions? Trying to gauge exactly what I broke :)

replace sv_edict_s to pointer broke comportabilty with old mods
because difirent size of edict_t
but pointer have different size in 64 and 32/qvm 
in this patch im calculate offset of actual entvars (pr_edict_offset), so this part of gedict not used now( not by mod, not by server)
im offer completly remove it from mod structures in next API version
same problem for gamedata and fields in qvm on 64bit server, but it will converted on load

**Comment by angeld29** [comment]
PR2_IsValidReadAddress broke QVM, 
allow read/ write outside vm memory wrong idea
this hack may work in 32 bit, but never in 64 bit
originally netnames for clients stored in mod memory, to allow mod using it
it requred update it in mod memory on server init, and on changing user name
as im see, some string also passed to mod by this hack
        PR_SetEntityString(ent, ent->v->netname, VersionStringFull());
	PR_SetEntityString(ent, ent->v->targetname, SERVER_NAME);
        PR_SetEntityString(ent, ent->v->model, sv.modelname);

changing this requred changes in mod( setup netnames pointers, mapname pointer, and if some mod use world-> netname/targetname get it by alternate way)

**Comment by qqshka** [comment]
duplicate

**Pull request closed without merging**
